cake-contrib/Cake.Npm

src/Cake.Npm/Cake.Npm.csproj, src/Cake.Npm/Install/NpmInstallSettingsExtensions.cs, src/Cake.Npm/NpmSettingsExtensions.cs
Add XML comment documentation files
=> (GH-41) Add documentation xml files

src/Cake.Npm/Namespaces.cs, src/Cake.Npm/NpmPublishAliases.cs, src/Cake.Npm/Publish/NpmPublishAccess.cs, src/Cake.Npm/Publish/NpmPublishSettings.cs, src/Cake.Npm/Publish/NpmPublishSettingsExtensions.cs, src/Cake.Npm/Publish/NpmPublisher.cs, tests/Cake.Npm.Tests/Publish/NpmPublishSettingsExtensionsTests.cs, tests/Cake.Npm.Tests/Publish/NpmPublisherFixture.cs, tests/Cake.Npm.Tests/Publish/NpmPublisherTests.cs
Add `NpmPublish` alias. Fixes #20.
Work in progress as it still needs proper testing.
=> (GH-20) Add support for npm publish

src/Cake.Npm/Cake.Npm.csproj
Use new Cake Contrib icon
Fixes #44
=> (GH-44) Use Cake Contrib icon

src/Cake.Npm/NpmRebuildAliases.cs, src/Cake.Npm/Rebuild/NpmRebuilSettingsExtensions.cs, src/Cake.Npm/Rebuild/NpmRebuildSettings.cs, src/Cake.Npm/Rebuild/NpmRebuilder.cs, tests/Cake.Npm.Tests/Rebuild/NpmRebuilderFixture.cs, tests/Cake.Npm.Tests/Rebuild/NpmRebuilderTests.cs
Add aliases for Npm Rebuild. Useful for dealing with https://github.com/sass/node-sass/issues/1918
Fixes #48
=> (GH-48) Add Npm Rebuild Aliases

CONTRIBUTING.md
=> (GH-61) Add contributing information

nuspec/nuget/Cake.Npm.nuspec, src/Cake.Npm.Tests/Cake.Npm.Tests.csproj, src/Cake.Npm/Cake.Npm.csproj
Build against Cake 0.26.0
Fixes #70
=> (GH-70) Build against Cake 0.26.0

src/Cake.Npm.Tests/Cake.Npm.Tests.csproj
Update XUnit and Shouldly to latest versions
=> Update XUnit and Shouldly

src/Cake.Npm.Tests/Ci/NpmCiToolFixture.cs, src/Cake.Npm.Tests/Ci/NpmCiToolTests.cs, src/Cake.Npm/Ci/NpmCiSettings.cs, src/Cake.Npm/Ci/NpmCiTool.cs, src/Cake.Npm/NpmCiAliases.cs
=> Add support for 'npm ci'

src/Cake.Npm.Tests/Prune/NpmPruneFixture.cs, src/Cake.Npm.Tests/Prune/NpmPruneRunnerTests.cs, src/Cake.Npm.Tests/Prune/NpmPruneSettingsExtensionsTests.cs, src/Cake.Npm/NpmPruneAliases.cs, src/Cake.Npm/Prune/NpmPruneRunner.cs, src/Cake.Npm/Prune/NpmPruneSettings.cs, src/Cake.Npm/Prune/NpmPruneSettingsExtensions.cs
added support for npm prune
Signed-off-by: Ryan Daniels <rdaniels6813@gmail.com>
Fixes #94
=> (GH-94) Add support for npm prune

src/Cake.Npm.Tests/AddUser/NpmAddUserFixture.cs, src/Cake.Npm.Tests/AddUser/NpmAddUserSettingsExtensionsTests.cs, src/Cake.Npm.Tests/AddUser/NpmAddUserTests.cs, src/Cake.Npm/AddUser/AuthType.cs, src/Cake.Npm/AddUser/NpmAddUser.cs, src/Cake.Npm/AddUser/NpmAddUserSettings.cs, src/Cake.Npm/AddUser/NpmAddUserSettingsExtensions.cs, src/Cake.Npm/NpmAddUserAliases.cs
Please review and let me know what changes need made. I have one failing test, but wanted to get some eyes on it. 
Fixes #78
=> (GH-78) Adding the AddUser Command

setup.cake
Pin Cake.Recipe to 1.0.0
Fixes #103
=> (GH-103) Pin Cake.Recipe to 1.0.0

nuspec/nuget/Cake.Npm.nuspec
As per Twitter conversation with NuGet PM:
https://twitter.com/adgrv/status/1127591787697061888
Resolves #105
=> (GH-105) Update NuGet metadata

src/Cake.Npm/NpmVersionAliases.cs
Fixes GH-113.
I have no good idea on how to test that, though.
=> Set RedirectStandardOutput as a default on NpmVersion

src/Cake.Npm/NpmVersionAliases.cs, src/Cake.Npm/Version/NpmVersionSettings.cs
Add overloads for NpmVersion which accept a settings object.
Fixes #115
=> (GH-115) Add overloads for NpmVersion which accept a settings object

README.md, docs/input/_Bottom.cshtml, docs/input/assets/css/override.less
with a link to GitHub discussions
fixes #128
=> (GH-128) replaced link to Gitter

src/Cake.Npm.Tests/Cake.Npm.Tests.csproj, src/Cake.Npm/Cake.Npm.csproj
Build against Cake 1.0.0
Fixes #130
=> (GH-130) Build against Cake 1.0.0

.appveyor.yml, nuspec/nuget/Cake.Npm.nuspec, src/Cake.Npm.Tests/Cake.Npm.Tests.csproj, src/Cake.Npm/Cake.Npm.csproj
=> (#138) Update Cake references to v2.0.0

nuspec/nuget/Cake.Npm.nuspec
=> (#134) Add cake-addin tag to NuGet package

recipe.cake
Disable Coveralls since it currently is failing
=> Disable Coveralls

src/Cake.Npm.Tests/BumpVersion/NpmBumpVersionToolTests.cs, src/Cake.Npm/BumpVersion/NpmBumpVersionSettings.cs
=> (GH-152) Add support for --allow-same-version

.appveyor.yml, nuspec/nuget/Cake.Npm.nuspec, src/Cake.Npm.Tests/Cake.Npm.Tests.csproj, src/Cake.Npm/Cake.Npm.csproj
Multi-target .NET 6, .NET 7 & .NET 8
Fixes #156
=> (GH-156) Multi-target .NET 6, .NET 7 & .NET 8

src/Cake.Npm.Tests/Cake.Npm.Tests.csproj, src/Cake.Npm/Cake.Npm.csproj
Updates to build against Cake 4.0
Fixes #155
=> Update to Cake 4.0

src/Cake.Npm.Tests/AddUser/NpmAddUserSettingsExtensionsTests.cs, src/Cake.Npm.Tests/AddUser/NpmAddUserTests.cs, src/Cake.Npm.Tests/BumpVersion/NpmBumpVersionToolTests.cs, src/Cake.Npm.Tests/Ci/NpmCiToolTests.cs, src/Cake.Npm.Tests/Install/NpmInstallSettingsExtensionsTests.cs, src/Cake.Npm.Tests/Install/NpmInstallerTests.cs, src/Cake.Npm.Tests/NpmSettingsExtensionsTests.cs, src/Cake.Npm.Tests/Pack/NpmPackerTests.cs, src/Cake.Npm.Tests/Prune/NpmPruneRunnerTests.cs, src/Cake.Npm.Tests/Prune/NpmPruneSettingsExtensionsTests.cs, src/Cake.Npm.Tests/RunScript/NpmScriptRunnerTests.cs, src/Cake.Npm.Tests/Set/NpmSetToolTests.cs, src/Cake.Npm.Tests/Update/NpmUpdateToolTests.cs, src/Cake.Npm.Tests/Version/NpmVersionToolTests.cs, src/Cake.Npm.Tests/ViewVersion/NpmViewVersionToolTests.cs, src/Cake.Npm/AddUser/NpmAddUserSettings.cs, src/Cake.Npm/AddUser/NpmAddUserSettingsExtensions.cs, src/Cake.Npm/Ci/NpmCiSettingsExtensions.cs, src/Cake.Npm/Install/NpmInstallSettings.cs, src/Cake.Npm/Install/NpmInstallSettingsExtensions.cs, src/Cake.Npm/NpmSettings.cs, src/Cake.Npm/NpmSettingsExtensions.cs, src/Cake.Npm/Prune/NpmPruneSettings.cs, src/Cake.Npm/Prune/NpmPruneSettingsExtensions.cs, src/Cake.Npm/Publish/NpmPublishSettingsExtensions.cs, src/Cake.Npm/Rebuild/NpmRebuildSettings.cs, src/Cake.Npm/Rebuild/NpmRebuildSettingsExtensions.cs, src/Cake.Npm/RunScript/NpmRunScriptSettings.cs
Clean up code and fix linting issues
=> Fix linting issues

.config/dotnet-tools.json, recipe.cake
Update to alpha version of Cake.Recipe 4
=> Update to Cake.Recipe 4 alpha

src/Cake.Npm.Tests/ExceptionAssertExtensions.cs, src/Cake.Npm.Tests/Exec/NpmExecFixture.cs, src/Cake.Npm.Tests/Exec/NpmExecRunnerTests.cs, src/Cake.Npm.Tests/Exec/NpmExecSettingsExtensionsTests.cs, src/Cake.Npm/Exec/NpmExecRunner.cs, src/Cake.Npm/Exec/NpmExecSettings.cs, src/Cake.Npm/Exec/NpmExecSettingsExtensions.cs, src/Cake.Npm/NpmExecAliases.cs
=> (GH-177) Add support for npm exec.
